### ISSUE TITLE
OperationFailure..

### ISSUE THREAD

**Issue by kaos** [lsjostro/flumelogger#14]
Using version 0.4.1:

```
Traceback (most recent call last):
3/14/2016 1:44:33 PM  File "/usr/lib/python2.7/site-packages/flumelogger/handler.py", line 102, in emit_one
3/14/2016 1:44:33 PM    self.eventserver.append(tevent, client)
3/14/2016 1:44:33 PM  File "/usr/lib/python2.7/site-packages/flumelogger/eventserver.py", line 170, in append
3/14/2016 1:44:33 PM    raise OperationFailure(e)
3/14/2016 1:44:33 PM  OperationFailure: object of type 'NoneType' has no len()
```

Maybe this has been addressed since the 0.4.1 release?

I'm looking into it, see if I can spot what it can be...

**Comment by ultrabug** [comment]
Hi @kaos, mind giving some context ? what's the object / line you're sending here ?

**Comment by kaos** [comment]
OK, I've found the issue.

The log line was just a string, like `"Flume enabled"`.. but the issue was the the `headers` dict passed to FlumeHandler during init. It contained `None`-values.. which apparently doesn't play nice with the thrift lib.
